services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rede-global   # <--- O Bot já devia ter isso
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL=${DB_SSL:-false}
      - ADMIN_WHATSAPP_NUMBER=${ADMIN_WHATSAPP_NUMBER}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - WEBHOOK_SIGNATURE_KEY=${WEBHOOK_SIGNATURE_KEY}
      - PYTHON_API_URL=${PYTHON_API_URL:-http://meu-secretario-api:8000}

  db:
    image: postgres:15-alpine
    container_name: postgres-central   # <--- GARANTA QUE O NOME ESTÁ AQUI
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-bot_whatsapp}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rede-global    # <--- ADICIONE ISSO AQUI!!!! (Faltava isso)

volumes:
  pgdata:

networks:
  rede-global:
    external: true
